version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - poetry install --with dev
      # Import docutils to test if it is correctly installed
      - python -c "import docutils; print(docutils.__version__)"

    pre_build:
      # Generating full API spec for geococo
     - sphinx-apidoc -o docs/ geococo/

sphinx:
  configuration: docs/conf.py