version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
      - uv sync --all-extras --dev 
    build:
      html:
        - uv run sphinx-apidoc -o docs/ geococo/
        - uv run sphinx-autogen docs/index.rst
        - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html
sphinx:
  configuration: docs/conf.py