version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      
    post_install:
      - $HOME/.local/bin/uv sync --all-extras --dev
      
    pre_build:
     - $HOME/.local/bin/uv run sphinx-apidoc -o docs/ geococo/

sphinx:
  configuration: docs/conf.py