name: Test and release
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pypi_release:
    name: "Releasing on PyPI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installing UV
        uses: astral-sh/setup-uv@v5

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          
      - name: Verifying dependencies
        id: lock
        run: uv lock --check
        
      - name: Installing dependencies
        id: sync
        run: uv sync --all-extras --dev

      - name: Running pytest
        id: test
        run: uv run pytest

      - name: Running linter
        id: lint
        run: uv run ruff check geococo --output-format=github
             
      - name: Running formatter
        id: format
        run: uv run ruff format geococo --diff
            
      # - name: Running type checker
      #   id: type
      #   run: uv run mypy geococo
      # - name: Checking code coverage
      #   id: coverage
      #   run: uv run pytest --cov=geococo --cov-fail-under=75

      - name: Parsing info
        id: info
        shell: bash
        run: |
          echo "RELEASE_NAME=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['name'])")" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")" >> $GITHUB_ENV

      - name: Build package
        id: build
        run: uv build
        if: steps.lock.outcome == 'success' && steps.sync.outcome == 'success' && steps.test.outcome == 'success' && steps.lint.outcome == 'success' && steps.format.outcome == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        
      - name: Publish package
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
        if: steps.build.outcome == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        if: steps.build.outcome == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          name: ${{ env.RELEASE_NAME }}
          path: dist/*

    outputs:
      RELEASE_NAME: ${{ env.RELEASE_NAME }}
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      PASSED_BUILD: ${{ steps.build.outcome }}

  github_release:
    name: "Releasing on Github"
    needs: pypi_release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Collect artifacts
        uses: actions/download-artifact@v4
        id: collect
        if: ${{ needs.pypi_release.outputs.PASSED_BUILD }} == 'success'

      - name: Upload artifacts 
        uses: softprops/action-gh-release@v2
        if: steps.collect.outcome == 'success'
        with:
          files: ${{ needs.pypi_release.outputs.RELEASE_NAME }}/*
          tag_name: ${{ needs.pypi_release.outputs.RELEASE_VERSION }}
          generate_release_notes: true
          prerelease: false
