name: Release on TestPyPi
on:
  workflow_dispatch: # Manual trigger (dev)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installing UV
        uses: astral-sh/setup-uv@v5

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          
      - name: Verifying dependencies
        id: lock
        run: uv lock --check
        
      - name: Installing dependencies
        id: sync
        run: uv sync --all-extras --dev

      - name: Build package
        id: build
        run: uv build
        if: steps.lock.outcome == 'success' && steps.sync.outcome == 'success'
        
      - name: Publish package
        run: uv publish --token ${{ secrets.TESTPYPI_API_TOKEN }} --index testpypi
        if: steps.build.outcome == 'success'
